### ISSUE TITLE
chromecast no cast destination found

### ISSUE THREAD

**Issue by anshprat** [jessfraz/dockerfiles#220]
Hi,

I am on Mac Sierra and am able to run chrome in docker with XQuartz using

docker run -it         --net host         --cpuset-cpus 0         --memory 512mb         -v /tmp/.X11-unix:/tmp/.X11-unix         -e DISPLAY=unix$DISPLAY         -v $HOME/Downloads:/root/Downloads         -v $HOME/.config/google-chrome/:/data               -v /dev/shm:/dev/shm         --name chrome     --security-opt seccomp:unconfined   -e DISPLAY=10.0.0.8:0  jess/chrome:beta

However chromecast is not found from the docker chrome (I have added the extension).

No Cast destinations found. Need help?

The only error I see in the docker running terminal after I search for chromecast is:

[1:1:1224/115700.713192:ERROR:CONSOLE(438)] "Uncaught TypeError: Cannot read property 'updateMaxDialogHeight' of null", source: chrome://media-router/media_router.js (438)

which looks like just an UI issue.

Ideas?

**Comment by jessfraz** [comment]
you arent in the same network as the chromecast. I would suggest looking into how network namespaces work. 1. if you are in a mac you are running in a virtual machine, then on the VM you are running in a linux network namespace. So yes, this means it cannot find the chromecast on your network because there are multiple levels of network you are in.
