### ISSUE TITLE
Very poor man's docker to install packages safely

### ISSUE THREAD

**Issue by jomagam** [jessfraz/dockerfiles#32]
I had this thought inspired by the containerized apps here. Ideally, when trying out a new but trusted app, I would only want to isolate the newly installed libraries and code, but be able to access the whole file system, run it as already existing user, find the PID "normally", etc... Do others share this sentiment ? Is there a framework for this ? I realize this would only use a small subset of what docker does, so it might be an independent project. So conceptually:
1. You specify a list of files/directories that are overlaid and cannot be shared with the host.
2. You specify a list of binaries that need to be started thru a wrapper that sets up the overlay before starting.

Profit. Thoughts ?

**Comment by RGD2** [comment]
You probably want to check out https://appimage.org/

I did have the thought also: To build random app from a github project, within a docker with minimal tool-chain setup (pref, one apt-get line), then once the 'make install' version works,  also use the appimage tools to build a 'built' version of the app, only copy it out and run it from the appimage on the host. Then I can lose the docker image that did the building.

I think that would be best of both worlds: Makes nice app images, and gives a way for small github project dev teams to agree on how their toolchain is set up. 

I am so very tired of projects failing to build because the dev team of random github project couldn't be bothered to find out what packages they depend on, expecting everyone to wade through dependency hell with cmake instead. After all, 'it works for them', probably on their decades old hand-tuned bespoke gentoo distro!

**Comment by jessfraz** [comment]
closing as this is not bugs with this repo, thanks! but feel free to discuss!
